version: '3'

tasks:
  build:
    dir: './build'
    cmds:
      - cmake .. -G Ninja
      - cmake --build .

  test:
    dir: './build'
    cmds:
      - cmake .. -G Ninja
      - cmake --build .
      - ./AssemblerTests

  clean:
    dir: './'
    cmds:
      - rm -rf build

        
